import { NewsItem } from '@/types/news';

export const MOCK_NEWS: NewsItem[] = [
  {
    id: 'mock-1',
    title: 'OpenAI anuncia novo modelo GPT-5 com capacidades revolucionárias',
    titleOriginal: 'OpenAI announces new GPT-5 model with revolutionary capabilities',
    description: 'A OpenAI revelou hoje seu mais novo modelo de linguagem, GPT-5, prometendo avanços significativos em raciocínio, matemática e compreensão contextual de longo prazo.',
    descriptionOriginal: 'OpenAI revealed today its newest language model, GPT-5, promising significant advances in reasoning, mathematics and long-term contextual understanding.',
    link: 'https://example.com/openai-gpt5',
    pubDate: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    source: 'TechCrunch AI',
    labels: ['OpenAI'],
    tags: ['Lançamento'],
    whyItMatters: 'Representa um salto significativo em capacidades de IA que pode impactar desde atendimento ao cliente até pesquisa científica.',
    featuredScore: 10,
  },
  {
    id: 'mock-2',
    title: 'Google DeepMind desenvolve IA que prevê estruturas de proteínas com 99% de precisão',
    titleOriginal: 'Google DeepMind develops AI that predicts protein structures with 99% accuracy',
    description: 'Pesquisadores do Google DeepMind criaram um sistema de IA que prevê estruturas de proteínas com precisão sem precedentes.',
    descriptionOriginal: 'Researchers at Google DeepMind have created a new AI system that predicts protein structures with unprecedented accuracy.',
    link: 'https://example.com/deepmind-proteins',
    pubDate: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    source: 'VentureBeat AI',
    labels: ['Google'],
    tags: ['Pesquisa'],
    whyItMatters: 'Acelera descoberta de medicamentos e pode reduzir custos de desenvolvimento farmacêutico em bilhões de dólares.',
    featuredScore: 9,
  },
  {
    id: 'mock-3',
    title: 'Meta lança ferramenta de IA para detectar deepfakes em tempo real',
    titleOriginal: 'Meta launches AI tool to detect deepfakes in real-time',
    description: 'A Meta anunciou uma ferramenta de IA capaz de detectar vídeos deepfake em tempo real.',
    descriptionOriginal: 'Meta announced a new AI tool capable of detecting deepfake videos in real-time.',
    link: 'https://example.com/meta-deepfake',
    pubDate: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
    source: 'The Verge AI',
    labels: ['Meta'],
    tags: ['Lançamento'],
    whyItMatters: 'Ajuda empresas a protegerem sua marca contra desinformação e fraudes baseadas em IA generativa.',
    featuredScore: 8,
  },
  {
    id: 'mock-4',
    title: 'Startup de IA levanta $500M para revolucionar educação personalizada',
    titleOriginal: 'AI startup raises $500M to revolutionize personalized education',
    description: 'Uma startup focada em educação com IA garantiu $500 milhões em financiamento para tutores virtuais adaptativos.',
    descriptionOriginal: 'An AI-focused education startup has secured $500 million in funding to develop adaptive virtual tutors.',
    link: 'https://example.com/edu-startup',
    pubDate: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    source: 'TechCrunch AI',
    labels: ['Startups'],
    tags: ['Aquisição'],
    whyItMatters: 'Sinaliza crescimento do mercado de EdTech com IA e novas oportunidades de investimento no setor.',
    featuredScore: 7,
  },
  {
    id: 'mock-5',
    title: 'Microsoft integra IA avançada ao Office 365 para automação de tarefas',
    titleOriginal: 'Microsoft integrates advanced AI into Office 365 for task automation',
    description: 'A Microsoft revelou novos recursos de IA no Office 365 que automatizam tarefas repetitivas.',
    descriptionOriginal: 'Microsoft revealed new AI features in Office 365 that can automate repetitive tasks.',
    link: 'https://example.com/microsoft-office-ai',
    pubDate: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    source: 'VentureBeat AI',
    labels: ['Microsoft'],
    tags: ['Atualização'],
    whyItMatters: 'Pode aumentar produtividade de equipes corporativas em até 30%, reduzindo tempo em tarefas administrativas.',
    featuredScore: 8,
  },
  {
    id: 'mock-6',
    title: 'União Europeia aprova nova regulamentação para IA generativa',
    titleOriginal: 'European Union approves new regulation for generative AI',
    description: 'O Parlamento Europeu aprovou diretrizes rigorosas para uso de IA generativa.',
    descriptionOriginal: 'European Parliament approved strict guidelines for the use of generative AI.',
    link: 'https://example.com/eu-ai-regulation',
    pubDate: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    source: 'TechCrunch AI',
    labels: ['Regulamentação'],
    tags: ['Regulamentação'],
    whyItMatters: 'Empresas operando na Europa precisam adaptar produtos de IA para compliance até o final do ano.',
    featuredScore: 9,
  },
  {
    id: 'mock-7',
    title: 'NVIDIA anuncia nova geração de GPUs otimizadas para treinamento de IA',
    titleOriginal: 'NVIDIA announces new generation of GPUs optimized for AI training',
    description: 'A NVIDIA apresentou sua nova arquitetura de GPU que promete treinar modelos 10x mais rápido.',
    descriptionOriginal: 'NVIDIA unveiled its new GPU architecture that promises to train models 10x faster.',
    link: 'https://example.com/nvidia-gpu',
    pubDate: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    source: 'The Verge AI',
    labels: ['NVIDIA'],
    tags: ['Lançamento'],
    whyItMatters: 'Reduz custos de infraestrutura de IA e permite que mais empresas desenvolvam modelos próprios.',
    featuredScore: 8,
  },
  {
    id: 'mock-8',
    title: 'Anthropic lança Claude 3.5 com maior contexto e raciocínio aprimorado',
    titleOriginal: 'Anthropic launches Claude 3.5 with longer context and improved reasoning',
    description: 'A Anthropic revelou a nova versão do Claude com janela de contexto de 200K tokens.',
    descriptionOriginal: 'Anthropic revealed the new version of Claude with 200K token context window.',
    link: 'https://example.com/anthropic-claude35',
    pubDate: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    source: 'VentureBeat AI',
    labels: ['Anthropic'],
    tags: ['Lançamento'],
    whyItMatters: 'Permite análise de documentos completos e contratos sem resumir, economizando tempo de advogados e analistas.',
    featuredScore: 8,
  },
  {
    id: 'mock-9',
    title: 'Google anuncia Gemini 2.0 com capacidades multimodais avançadas',
    titleOriginal: 'Google announces Gemini 2.0 with advanced multimodal capabilities',
    description: 'O Google revelou o Gemini 2.0 que processa texto, imagem, áudio e vídeo simultaneamente.',
    descriptionOriginal: 'Google revealed Gemini 2.0 that processes text, image, audio and video simultaneously.',
    link: 'https://example.com/google-gemini2',
    pubDate: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    source: 'TechCrunch AI',
    labels: ['Google'],
    tags: ['Lançamento'],
    whyItMatters: 'Abre possibilidades para aplicações de IA em vídeo análise, educação interativa e acessibilidade.',
    featuredScore: 9,
  },
  {
    id: 'mock-10',
    title: 'Startup brasileira de IA recebe investimento de $50M',
    titleOriginal: 'Brazilian AI startup receives $50M investment',
    description: 'Uma startup de São Paulo especializada em IA para agronegócio levantou investimento Series B.',
    descriptionOriginal: 'A São Paulo-based startup specializing in AI for agriculture raised Series B funding.',
    link: 'https://example.com/br-startup',
    pubDate: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    source: 'VentureBeat AI',
    labels: ['Startups'],
    tags: ['Aquisição'],
    whyItMatters: 'Demonstra crescimento do ecossistema de IA na América Latina e oportunidades no agronegócio.',
    featuredScore: 6,
  },
  {
    id: 'mock-11',
    title: 'Meta anuncia LLaMA 3 disponível para uso comercial',
    titleOriginal: 'Meta announces LLaMA 3 available for commercial use',
    description: 'A Meta liberou o LLaMA 3 para uso comercial sem restrições de licenciamento.',
    descriptionOriginal: 'Meta released LLaMA 3 for commercial use without licensing restrictions.',
    link: 'https://example.com/meta-llama3',
    pubDate: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    source: 'The Verge AI',
    labels: ['Meta'],
    tags: ['Lançamento'],
    whyItMatters: 'Permite que empresas desenvolvam produtos de IA sem custos de API, reduzindo barreiras de entrada.',
    featuredScore: 8,
  },
  {
    id: 'mock-12',
    title: 'OpenAI e Microsoft expandem parceria com $10 bilhões em investimento',
    titleOriginal: 'OpenAI and Microsoft expand partnership with $10 billion investment',
    description: 'Microsoft anuncia investimento adicional de $10 bilhões na OpenAI.',
    descriptionOriginal: 'Microsoft announces additional $10 billion investment in OpenAI.',
    link: 'https://example.com/openai-microsoft',
    pubDate: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
    source: 'TechCrunch AI',
    labels: ['OpenAI', 'Microsoft'],
    tags: ['Aquisição'],
    whyItMatters: 'Consolida posição da Microsoft no mercado de IA empresarial e acelera integração com Azure.',
    featuredScore: 9,
  },
];
